### PR TITLE
Fix model and program logging

### LINKED ISSUE #1341: Fix luma.gl logging
Was causing performance issues, so it was put behind a flag in 8.0. Re-enable in a way that doesn't affect performance.

Affecting deck.gl users: https://github.com/uber/deck.gl/issues/4195

### PR DESCRIPTION
**Pull request by tsherif**
Fixes #1341

### CODE REVIEW

File: modules/webgl/src/classes/program.js [hunk 1]
```diff
@@ -132,7 +131,7 @@ export default class Program extends Resource {
       this.setUniforms(uniforms || {});
     }
 
-    if (this.debug && logPriority !== undefined) {
+    if (log.priority >= 2 && logPriority !== undefined) {
```
Comment (Pessimistress) [inline modules/webgl/src/classes/program.js]: This should be `log.priority >= logPriority`?

Comment (tsherif) [reply modules/webgl/src/classes/program.js]: Done.

**Comment by tsherif** [comment]
Can do.
