### PR TITLE
Fix resource leaks in Framebuffer and multipass classes

### LINKED ISSUE #1201: How do I free the resources consumed by a multipass renderer?
When I create a multipass renderer, framebuffers are created inside the RenderState object. How do I free these framebuffers, i.e. do I need to delete the multipass renderer? If so, how do I do that?

### PR DESCRIPTION
**Pull request by 1chandu**
Fixes #1201 

#### Background
- Fix resource leaks in `Frameubffer` class
- Fix resource leaks in `multipass` classes
- Add unit tests.

#### Change List
- Fix resource leaks in Framebuffer and multipass classes

### CODE REVIEW

File: modules/webgl/src/classes/framebuffer.js [hunk 1]
```diff
@@ -128,6 +129,12 @@ export default class Framebuffer extends Resource {
     }
   }
 
+  delete() {
+    for (const resource of this.resources) {
```
Comment (ibgreen) [inline modules/webgl/src/classes/framebuffer.js]: Don't we already have references to these resources in `this.attachments`? 

I would prefer walking that object and deleting/clearing rather than adding a second set of references (that could get "out of sync" during maintenance of this class).

File: modules/core/src/multipass/copy-pass.js [hunk 2]
```diff
@@ -25,6 +25,10 @@ export default class CopyPass extends Pass {
     this.clipspace = new ClipSpace(gl, {id: 'copy-pass', fs});
   }
 
+  delete() {
+    super.delete();
+    this.clipspace.delete();
+  }
   _renderPass({inputBuffer}) {
```
Comment (ibgreen) [inline modules/core/src/multipass/copy-pass.js]: Nit: Add empty line

File: modules/webgl/src/classes/framebuffer.js (hunk 1 above)
Comment (1chandu) [reply modules/webgl/src/classes/framebuffer.js]: `this.attachments` could be pointing to resources provided by the user of this class and not owned by it, so added a new list to track all resources created by this class.

Comment (ibgreen) [reply modules/webgl/src/classes/framebuffer.js]: I guess that is a fair point. Since several people are working on resource managers, I am happy to defer to ongoing work in that area.

Comment (tsherif) [reply modules/webgl/src/classes/framebuffer.js]: I'd suggest renaming to something like `ownResources` then, to make it clear that it's resources managed by the framebuffer.
