### PR TITLE
Fix usage with rollup

### LINKED ISSUE #1265: Fix webpack's headless hack to allow use in rollup
#### Actual Result
Using luma.gl with rollup results in the app crashing at launch with:
```
module is not defined
```
#### Expected Result
The app loads as expected.

#### Reproduce Steps
```
yarn install luma.gl
```
```
import {AnimationLoop} from 'luma.gl';
```

will submit a PR to fix in a minute.

### PR DESCRIPTION
**Pull request by darionco**
This hack, although works in webpack, breaks usage in the browser when packaging with rollup.
Adding a `try/catch` block fixes the issue. Fixes #1265

#### Change List
- Surrounded hack in a `try/catch` block.

### CODE REVIEW

File: modules/webgl/src/webgl-utils/webgl-types.js [hunk 1]
```diff
@@ -18,7 +18,12 @@ typical configuration for isorender applications running on the server.`;
 // TODO(Tarek): OOGLY HACK to avoid webpack requiring headless
 //   browser bundles. Will be removed in 8.0 when we
 //   remove automatic headless context creation
-const m = module;
+let m;
```
Comment (ibgreen) [inline modules/webgl/src/webgl-utils/webgl-types.js]: Let's add a note that this try/catch fixes rollup support to help future webpack-using maintainers.

Comment (darionco) [reply modules/webgl/src/webgl-utils/webgl-types.js]: Added.
```
// NOTE: Rollup does not process the line `const m = module;`
//   and writes it out verbatim in its final output, which ends
//   up falling over in browser environments at runtime. Added
//   a `try/catch` block to fix usage in rollup builds.
```
