### PR TITLE
Fix injected declarations

### LINKED ISSUE #1151: Shader hooks should be injected after declarations
#### Actual Result

The `#decl` injection point is appended after the hook definitions, making it impossible to use custom uniforms in the hooks.

#### Expected Result

Hooks should be defined after the custom declarations.

#### Reproduce Steps

```js
assembleShaders(gl, {
  vs: '',
  fs: `
void main() {
  gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
  FILTER_COLOR(gl_FragColor);
}
  `,
  inject: {
    'fs:#decl': `uniform bool shouldDraw;`,
    'fs:FILTER_COLOR': `if (!shouldDraw) discard;`
  }
});
```

Returns the following fragment shader:

```glsl
...

precision highp float;

void FILTER_COLOR(vec4 color) {
  if (!shouldDraw) discard;
}

uniform bool shouldDraw;

void main() {
  gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
  FILTER_COLOR(gl_FragColor);
}
```

Which results in GLSL compilation error:

```
^^^ ERROR: 'shouldDraw' : undeclared identifier
```

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

### PR DESCRIPTION
**Pull request by tsherif**
Ensure that declarations are injected before module functions. Fixes #1151

### CODE REVIEW

File: modules/shadertools/src/lib/assemble-shaders.js [hunk 1]
```diff
@@ -151,6 +151,9 @@ ${isVertex ? '' : FRAGMENT_SHADER_PROLOGUE}
     }
   }
 
+  // For injectShader
+  assembledSource += '\n\n__LUMA_INJECT_DECLARATIONS__\n\n';
```
Comment (Pessimistress) [inline modules/shadertools/src/lib/assemble-shaders.js]: Import constant from `inject-shader.js`?

Comment (tsherif) [reply modules/shadertools/src/lib/assemble-shaders.js]: Done.
