### PR TITLE
Convert any v3 texture parameters to v4

### LINKED ISSUE #197: Ensure compatibility with luma.gl v3 Texture parameters
We need to add test cases in luma.gl to cover the failed size deduction in https://github.com/uber/deck.gl/issues/683.

Landing https://github.com/uber/deck.gl/pull/684 will help debugging in deck.gl

### PR DESCRIPTION
**Pull request by 1chandu**
Fixes #197

### CODE REVIEW

File: src/webgl/texture.js [hunk 1]
```diff
@@ -112,6 +112,13 @@ export const TEXTURE_FORMATS = {
   // [GL.COMPRESSED_RGBA_ATC_INTERPOLATED_ALPHA_WEBGL]: {compressed: true, gl1: ETC1}
 };
 
+const V3_TO_V4_OPTIONS_MAP = {
```
Comment (1chandu) [inline src/webgl/texture.js]: @ibgreen , in v3 branch, setParameters() has following arguments:
```
setParameters({
    magFilter,
    minFilter,
    wrapS,
    wrapT,
    // WEBGL2
    wrapR,
    baseLevel,
    maxLevel,
    minLOD,
    maxLOD,
    compareFunc,
    compareMode
  }) {
```
Assuming I should add all of them, can you please confirm?

File: src/webgl/texture.js [hunk 2]
```diff
@@ -608,6 +626,21 @@ export default class Texture extends Resource {
   }
   */
 
+  // OVERRIDES
+  setParameters(parameters) {
```
Comment (1chandu) [inline src/webgl/texture.js]: Are these deprecated options present in `opts.parameters` or in `opts` (in constructor), if it is in `opts`,  I may have to extract them , add it to `parameters` before calling `setParameters` in constructor ?

File: src/webgl/texture.js (hunk 1 above)
Comment (ibgreen) [inline src/webgl/texture.js]: I am pretty sure the WebGL2 parameters have never been used, since there were other issues with the WebGL2 texture support in v3.

So for compatibility reasons, the answer is no.

We could decide to keep this API, it is a little easier to use than GL ENUMS. Although it would be the only class for which we have our own parameters. What do you think?

File: src/webgl/texture.js (hunk 2 above)
Comment (ibgreen) [inline src/webgl/texture.js]: Yes they are in opts, not in opts.parameters. You need to extract them (there is a code example in the issue).

File: src/webgl/texture.js (hunk 1 above)
Comment (1chandu) [inline src/webgl/texture.js]: Either way is fine, not a big difference but I would opt for GL ENUM style, couple of reasons
1. Don't see much advantage other than shorter names.
2. Since we are using enums in other places, lets keep same style every where.

Comment (ibgreen) [inline src/webgl/texture.js]: >  I would opt for GL ENUM style 

Sounds good! Let's just add backwards compatibility support for the old opts then, with deprecation warnings.

File: src/webgl/texture.js (hunk 2 above)
Comment (1chandu) [inline src/webgl/texture.js]: Done!

File: src/webgl/texture.js (hunk 1 above)
Comment (1chandu) [inline src/webgl/texture.js]: Done!
